//
//  VPNObjcHelp.h
//  loginIn
//
//  Created by jumpapp1 on 16/2/29.
//  Copyright © 2016年 jumpapp1. All rights reserved.
//

#import <Foundation/Foundation.h>
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_3G;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_3GS;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_4;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_4S;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_5;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_5C;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_5S;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_6;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPHONE_6PLUS;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPOD_TOUCH_4;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPOD_TOUCH_5;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPOD_TOUCH_3;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPOD_TOUCH_2;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPOD_TOUCH;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPAD_3;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPAD_2;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPAD_1;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPAD_MINI;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IPAD_AIR;

FOUNDATION_EXPORT NSString *const JZ_DEVICE_IOS_MODEL_IPAD;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IOS_MODEL_IPHONE;
FOUNDATION_EXPORT NSString *const JZ_DEVICE_IOS_MODEL_IPOD_TOUCH;

@interface VPNObjcHelp : NSObject
#pragma mark - __System__


NSString * currentDeviceModl();
NSString * currentDeviceIOSModel();

#pragma mark - __String__

NSString * NSStringFromFloat(float floatV);
NSString * NSStringFromInt(int intV);
@end
